
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 27 20:47:00 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 20;
  public static final int MAP = 16;
  public static final int LBRACKET = 42;
  public static final int CONST = 6;
  public static final int GREATEROREQUAL = 29;
  public static final int COMMENT = 44;
  public static final int NUMCONST = 46;
  public static final int NOTEQUAL = 27;
  public static final int LPAREN = 38;
  public static final int SEMI = 35;
  public static final int GREATER = 31;
  public static final int CONTINUE = 15;
  public static final int LESS = 30;
  public static final int MINUS = 23;
  public static final int RPAREN = 39;
  public static final int AND = 32;
  public static final int OR = 33;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 25;
  public static final int DIV = 18;
  public static final int LESSOREQUAL = 28;
  public static final int PLUS = 21;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 22;
  public static final int RETURN = 12;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 26;
  public static final int LAMBDA = 24;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 17;
  public static final int MOD = 19;
  public static final int IDENT = 45;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int COLON = 34;
  public static final int LBRACE = 40;
  public static final int ELSE = 5;
  public static final int READ = 11;
  public static final int CHARCONST = 47;
  public static final int WHILE = 8;
  public static final int RBRACE = 41;
  public static final int BOOLCONST = 48;
  public static final int FULLSTOP = 36;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int PRINT = 10;
}

